### ISSUE TITLE
使用 react 重写 jamstack 的官网

### ISSUE THREAD

**Issue by happypeter** [happypeter/jam#1]
https://jamstack.org/

源码在 https://github.com/jamstack/jamstack.org

不过不是用 react 写的。

@静文 把这个网站用 react 重写一遍，回头我来翻译。

**Comment by happypeter** [comment]
不要用 create-react-app 搭建环境了，用 gatsby 。

网上有一些参考资料。https://www.cnblogs.com/rongfengliang/p/7783083.html

我这两天也会发 gatsby 的课程。

**Comment by happypeter** [comment]
参考这个视频中的内容，基本上就可以完成本任务了：https://haoqicat.com/gatsby/1-hello

**Comment by youngjingwen** [comment]
好的

**Comment by youngjingwen** [comment]
@happypeter 老师，目前完成了 首页 、Best Practices 、Examples、页面样式，代码上传吗？

**Comment by happypeter** [comment]
嗯，参考 https://haoqicat.com/gatsby/9-deploy

**Comment by youngjingwen** [comment]
@happypeter 老师，我按照课程部署，打开 https://happypeter.github.io/jam/ 找不到页面

**Comment by happypeter** [comment]
文件都上传了，但是 gh-pages 上没有一个顶级的 index.html

**Comment by happypeter** [comment]
本地运行  npm run develop 能跑吗？

运行 npm run build 之后，看看 public/ 文件夹下，有顶级位置的 index.html 码？

**Comment by youngjingwen** [comment]
可以运行npm run develop

 public/ 文件夹下，顶级位置有 index.html

**Comment by happypeter** [comment]
那手动把 public/ 下的内容上传到 gh-pages 分支就好了。

**Comment by youngjingwen** [comment]
目前仓库 gh-pages 分支顶级位置有 index.html

**Comment by youngjingwen** [comment]
老师，master 分支需要上传代码吗

**Comment by happypeter** [comment]
上传吧。

**Comment by happypeter** [comment]
可能是 gatsby-config.js 中的那个配置写的有问题

```
pathPrefix: `/jam`
```

写成这样应该就可以了。

**Comment by youngjingwen** [comment]
配置路径我写的是 pathPrefix: `/jam`

**Comment by youngjingwen** [comment]
我把代码上传到 master 分支了，老师您看一下

**Comment by happypeter** [comment]
我这边下载了你的代码，然后直接 npm run deploy ，结果居然可以了，https://happypeter.github.io/jam


😆

**Comment by happypeter** [comment]
电脑上打开效果完美。下一步把响应式做一下，保证手机微信里面可以完美显示。

**Comment by happypeter** [comment]
Good job!

**Comment by youngjingwen** [comment]
我也是 npm run deploy ,  目前 Community 页面没有完成，没有添加响应式，网页 header 效果我不太会做。老师看一下还有什么要改的吗

**Comment by youngjingwen** [comment]
好的

**Comment by happypeter** [comment]
header 效果，可以参考他们的源码，挑战一下，不行我再动手试试。

**Comment by youngjingwen** [comment]
@happypeter 老师，首页添加完响应式了，您 npm run deploy  一下看下效果

**Comment by happypeter** [comment]
我这里就是下载你源码，装包，然后 npm run deploy 就可以部署到 gh-pages 了，

```
➜  jam git:(master) ✗ node -v
v8.4.0
➜  jam git:(master) ✗
```

你看看你 node 版本，不行升级一下。

**Comment by happypeter** [comment]
效果挺棒的，https://happypeter.github.io/jam/Examples 有点问题，chrome 开发者工具中打开就能看到。

**Comment by happypeter** [comment]
其他几个有 ul 的也是有点样式问题。

**Comment by happypeter** [comment]
另外就是，响应式的导航栏，首页上直接打开没问题，切换到其他页面，再点汉堡按钮，有的时候打不开，有的时候导航栏有部分隐藏了。这个要稍微修复一下。

**Comment by youngjingwen** [comment]
@happypeter 老师其它页面响应式我还没有写，只是首页添加了响应式，其它页面导航栏问题，可能是响应式没有做好。

**Comment by happypeter** [comment]
对

**Comment by youngjingwen** [comment]
Examples 页面什么问题？ 我在 chrome 开发者工具中没有看到

**Comment by happypeter** [comment]
各个图片下面的大标题下面的列表文字错位了。

**Comment by youngjingwen** [comment]
@happypeter 老师我把代码上传了，我 npm run deploy 还是不行

**Comment by happypeter** [comment]
我又 deploy 了

**Comment by happypeter** [comment]
效果很棒啊，厉害！

**Comment by youngjingwen** [comment]
@happypeter 老师 header 部分完成了 您看一下

**Comment by happypeter** [comment]
部署了。

**Comment by happypeter** [comment]
我感觉已经非常好了。
