### ISSUE TITLE
加载进度条

### ISSUE THREAD

**Issue by happypeter** [happypeter/jam#2]
进入首页，然后点 Example 页的时候，有时会等很久，有时候甚至会一直切换不过去。

这个可以加一个  https://github.com/happypeter/haoduoshipin/blob/master/gatsby-config.js#L36

这个插件可以优化一下体验。

**Comment by youngjingwen** [comment]
@happypeter 老师 代码上传了

**Comment by happypeter** [comment]
部署了，体验非常棒
